name: Deploy to Production

on: workflow_dispatch
  
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'main'
          target_branch: 'production'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
